### ISSUE TITLE
Rename classes and pages to represent function

### ISSUE THREAD

**Issue by pjeli** [paypal/NNAnalytics#10]
Today there are several classes in NNA that are in need of renaming.

Here is a list of several that come to mind and one's that others have proposed:

SuggestionsEngine -> StatusEngine
NNLoader -> NameNodeAnalyticsMain
NNAnalyticsRestAPI -> NameNodeAnalyticsWebServer
suggestion.html -> status.html
custom.html -> histogram.html
tokens.html -> users.html

These are just some of the renames. If anyone comes up with others please post them here. Would be nice to get them out in one swoop for now if we can.

Please keep in mind that changing NNLoader and NNAnalyticsRestAPI will likely affect tests and shell scripts that launch NNA so extra attention needs to be made on renaming those classes.

**Comment by zero45** [comment]
Some additional things to rename:
java/SecurityConfiguration -> NNAConfiguration or AppConfiguration
config/security.properties -> nna.properties or application.properties
bin/nnloader -> nna_launcher? Could use suggestions here...

**Comment by pjeli** [comment]
Most of this work is covered now. Closing.
