### ISSUE TITLE
Configuration setup in RBF-enabled clusters

### ISSUE THREAD

**Issue by lukmajercak** [paypal/NNAnalytics#113]
When RBF is enabled in HDFS, we need to call NameNode.initializeGenericKeys. Otherwise, just copying the config from a standby NN is not going to work.

**Comment by lukmajercak** [comment]
For example, JN path for shared edits dir has to contain the nameservice id at the end, which is appended by NameNode.initializeGenericKeys. 

Otherwise, NNAnalytics fails with:
![image](https://user-images.githubusercontent.com/3524735/44818059-74f10300-ab9c-11e8-8f32-ed56f8286e6d.png)

**Comment by zero45** [comment]
Oh very neat! 

I see why you went with a custom version of Hadoop now as per earlier messages. :) Looking forward to RBF in HDFS.

Yeah I never make that call. We can add it into `NNLoader.load()` most likely, or maybe at beginning of `WebServerMain.main()`. Looking forward to the PR for this.

**Comment by pjeli** [comment]
I am going to close this. I realized this will not be a concern once we are in Apache as we don't actually care how the NameNode bootstraps -- we will just care that we can attach to a GSet of INodes.

In the Apache version we will run as an additional Jersey HTTP server within the NameNode by launching as a NameNodePlugin.
