### ISSUE TITLE
Parameterize 'bin/nn_loader'

### ISSUE THREAD

**Issue by zero45** [paypal/NNAnalytics#125]
Today one must manually update the run script in `bin/nn_loader` in order to adjust things like memory heap settings, garbage collection, etc. 

Today if one were to install the 1.3 release package, modify the `nn_loader` script in some way, and then create their own version package and upgrade to that, their `nn_loader` changes will get reset.

There are some properties in there that would be nice to parameterize via perhaps sourcing another file for so that we don't need to update the main runscript after every upgrade.

Then we simply have to define the other file as a CONFIG type in the packaging so that its not updated / changed in every upgrade (like we do now for security.properties).

**Comment by akshatgit** [comment]
Good idea, 
FYI PermGen is deprecated in Java 8 (PermSize and MaxPermSize). We still have these args in nn_loader. 
Ref: [https://stackoverflow.com/questions/18339707/permgen-elimination-in-jdk-8](url)

**Comment by zero45** [comment]
Thanks @akshatgit -- I'll reflect that in the PR.
