### ISSUE TITLE
Tokens endpoint should provide usernames who never had a token issued

### ISSUE THREAD

**Issue by rsmcelroy** [paypal/NNAnalytics#142]
Use case: I'm looking to remove users who have never used their account and have not used the cluster in some time.  The tokens report shows the last token issued for each user but not for any users that have never been issued one.  Sometimes accounts are created and not used.  It would be valuable to include users that have never been issued tokens as well.  Then we can easily use it as a purge list.

**Comment by zero45** [comment]
Makes sense! Marking this as part of 1.5.0 as well.
