### ISSUE TITLE
Improve tokens.html and tidy.html to link to users

### ISSUE THREAD

**Issue by rsmcelroy** [paypal/NNAnalytics#145]
Right now there are two columns on the tokens report.  The account and the date.   I'd like to add their number of files total, space consumed.  Also, add a link back to the suggestions page for that user so investigation can happen more quickly.

**Comment by zero45** [comment]
While this seems like a simple change there is actually a lot to process here.

For (1), I think adding a `<a href=./suggestions.html?username=USER>USER</a>` would be really simple on tokens.html; adding the files total and space consumed is tricky as we'd have to make a 2nd API call to do that properly.

I am thinking of doing another way -- modifying the `/suggestions` API to allow a way to get a dump of all users and all their usages and suggestions information. Currently the `/suggestions` API can only fetch information about 1 specific user or the entire system (if no user is specified). We need a way to call that endpoint that can give a giant JSON of all users -- that will allow us to create a better version of the hidden `tidy.html` page that just makes 1 call and then we can make a pretty table like @TheShrug  did in `metrics.html`.

**Comment by zero45** [comment]
Apologies @rsmcelroy, I am re-titling this to reflect changes required.

**Comment by zero45** [comment]
Example view of new `users.html` page which will showcase this:

![screen shot 2018-10-24 at 4 08 17 pm](https://user-images.githubusercontent.com/2126448/47466655-1b294580-d7a7-11e8-8bd1-fdcddf472ec9.png)

**Comment by rsmcelroy** [comment]
Looks great.  This helps a lot.

**Comment by zero45** [comment]
This is now committed.
