### ISSUE TITLE
Improve users.html page by adding percentage of old files

### ISSUE THREAD

**Issue by zero45** [paypal/NNAnalytics#151]
A trivial improvement that can be made to `users.html` is to add a column to the table showcasing the percentage of files that are over 1 year old. The data is already there in the JSON provided; just need to perform the percentage (utility method exists in `nna.utility.js`) and then expose it in the table.

**Comment by zero45** [comment]
Not today. Look at #138. We need to get the information, cache it, and then expose it so we can table it. I also want to avoid putting everything into `/users.html`. If we want to represent block information it should be in a different table. 

What value are you looking to get out of `average block size`? Do you mean `average file size`? Or maybe the # of blocks they have (and then you can get the average yourself)? Remember that by clicking on the username you can get the breakdown of the user too.

`/users.html` is evolving moreso towards a finder of "users that aren't using the cluster anymore".

**Comment by rsmcelroy** [comment]
Makes sense.  Table the avg file/block request.  I’ll get it another way.  I don’t want to see users.html get bloated.  

Russ

**Comment by rsmcelroy** [comment]
Anything new on this one?  Looking forward to it being released.

**Comment by zero45** [comment]
This is committed now. Just need to release 1.5.1.
