### ISSUE TITLE
Improve quotas.html to use datatables

### ISSUE THREAD

**Issue by pjeli** [paypal/NNAnalytics#153]
Today `/quotas.html` is a secret HTML page that simply lists all the HDFS paths that have quotas. We can better represent the information from here in `datatables` and let users sort and check what is the most urgent on client-side.

**Comment by zero45** [comment]
Screenshot of example improvement:

![screen shot 2018-10-30 at 4 38 04 pm](https://user-images.githubusercontent.com/2126448/47757152-596cac00-dc62-11e8-87b9-cc5a22c27a7f.png)
