### ISSUE TITLE
Move documentation to ReadTheDocs

### ISSUE THREAD

**Issue by zero45** [paypal/NNAnalytics#2]
It would be good to have a page dedicated to how the web API works and whats available the end user. Of course this would be subject to change as we develop NNA.

A couple other useful things would be to decide on how to maintain the documentation. Should it just be .md files? Maybe an external site? Wiki pages? Not clear for me on what a good standard is and am looking out to others for guidance.

**Comment by zero45** [comment]
@Dee-Pac -- I think for now lets start out with just getting ReadTheDocs up for NNA and splitting out the README into individual documentation. We can then expand on each on in separate issues.

**Comment by Dee-Pac** [comment]
@zero45 just started working on this one... will send a PR soon.

**Comment by zero45** [comment]
Nice. Thank you @Dee-Pac. I have created https://nnanalytics.readthedocs.io/.
Will review tomorrow morning. Quick scan things looked good though.

**Comment by zero45** [comment]
Changing name of title to reflect what we are addressing.
