### ISSUE TITLE
Make excessive logging be DEBUG only

### ISSUE THREAD

**Issue by pjeli** [paypal/NNAnalytics#207]
Currently all login successes are logged. This is the majority of what makes it to the .log or .out file. We can lessen the amount of logging significantly if we make the `Login success via {} for: {} at {}`and the `Time to convert object to {} of {} chars took: {} ms` to be DEBUG logging messages only.

**Comment by kunalmulwani** [comment]
@pjeli It requires the log type messages to be changed from info to debug. Is there anything else that I am missing?

**Comment by pjeli** [comment]
No that's it. Very simple change.

**Comment by pjeli** [comment]
Committed. Thank you, @kunalmulwani.
