### ISSUE TITLE
support analysis on specific path

### ISSUE THREAD

**Issue by seanlook** [paypal/NNAnalytics#233]
I don't find any filters that allowed me to analysis like fileCount on specific path. Does it support or will it plan to done?

May like `/filter?set=files&filters=fileSize:eq:0&path=/a/b/`

**Comment by pjeli** [comment]
It can definitely be done today. You would do it like so:
`/filter?set=files&filters=fileSize:eq:0&path:startsWith:/a/b/&sum=count`

If you drop the `&sum=count` part you will get a list / dump of all the file paths.

**Comment by pjeli** [comment]
The above example will traverse the entire subtree of `/a/b/`, if you meant ONLY under `/a/b/` specifically, and none of its subdirs, then you could do it like so:

`/filter?set=files&filters=fileSize:eq:0,path:startsWith:/a/b/,depth:eq:3&sum=count`

That would mean fetching all files that are under `/a/b/`, but only at depth level 3 (/a/b/file1, /a/b/file2, etc), and that are empty.

Hope this helps.

**Comment by pjeli** [comment]
Hi @seanlook, did these filters do the trick for you?

**Comment by seanlook** [comment]
Yes, that's what I need.
I'm not running NNA now. How much time it will cost when there's 20 million files under the entire subtree `/a/b/`  ?

Thank you.

**Comment by pjeli** [comment]
It really depends on how many files / dirs there are in your entire system and how many cores are available on your machine. It could take anywhere between 100ms to about 12 seconds depending on your system.

If you have less than 100M total files and directories and more than 30 physical cores it will likely complete in well under a second.

**Comment by pjeli** [comment]
This rest of this conversation is probably better suited for Gitter; just direct message me there as @pjeli - https://gitter.im/NNAnalytics/Lobby. Going to close this now. Thank you!
