### ISSUE TITLE
Collect the dubiously metrics form top endpoint

### ISSUE THREAD

**Issue by YanjunTian** [paypal/NNAnalytics#253]
Hi team, 
I collect the dubiously metrics data from http://192.168.10.2:8080/top endpoint as below :
![github_nna_top](https://user-images.githubusercontent.com/50485391/60562802-abcf1100-9d8b-11e9-96cd-e2a8459b32b6.png)

actually, our trend of data don't have such tremendous change.
welcome any suggestion from you guys , 
thanks

**Comment by pjeli** [comment]
Hi @YanjunTian,

Regarding `/top`, the way I have primarily been using it is as the following call `/top?limit=1`. That way I only see the top "causer" for each issue.

Now if the user / path changes, that means something else became the top issue, or if they begin to spike in usage, I know to alert / take a look as well.

Trending `/top` purely for visualization may not be that useful -- the better use is in detecting `/top` CHANGES; likely by adding Kapacitor or some other alerting mechanism.

**Comment by YanjunTian** [comment]
Hi Plamen Jeliazkov,
Thanks so much for your suggestion which is useful for me.
Have a nice day.
BR//Yanjun

**Comment by pjeli** [comment]
Thanks @YanjunTian! I’ll close this now. If you have anymore questions you can reach me on Gitter or open another issue. :)
