### ISSUE TITLE
What is the report generation strategy?

### ISSUE THREAD

**Issue by Viking-Bird** [paypal/NNAnalytics#254]
Hello, I am very interested in this tool. I would like to know, is this report generated at regular intervals every day? Which parameter controls it?

**Comment by pjeli** [comment]
Hi @Viking-Bird - sure let me break it down for you.

Code-wise, the main controller for the report generation is the SuggestionEngine.java class. It is runs in a background thread once NNA is started (and namespace is loaded).

The SuggestionEngine will sequentially run through a series of queries that obtain total counts as well as several histograms. The results of each query will stay in memory until all the queries are complete, then it will switch the old report with the new one - this is subject to change but just how it does it now.

The report will take as long as it needs to, but as of NNA 1.6.3+ these are the times I am seeing:
15 minutes for a 350M to 400M files/dirs cluster.
5 to 10 minutes minutes for a 150M to 200M files/dirs cluster. 
Less than a minute for 10-20M files/dirs cluster.

Once the report is generated, the thread sleeps for a configurable amount of time in `application.properties`. The configuration property is `nna.suggestions.reload.sleep.ms`.
By default it sleeps for 900000 ms, which is 15 minutes. You can change this to 0 and it will constantly be generating reports as soon as it can. Warning: this will heavily strain the CPUs on that system.

Once you are up and running, the NNA status page, `/suggestion.html` will show you the following 3 clocks:
![Screen Shot 2019-07-03 at 10 42 33 AM](https://user-images.githubusercontent.com/2126448/60613248-6278c480-9d7f-11e9-9334-4eaf3a9bd2fa.png)

The left most clock tells you how long the report took to generate: HH:MM:ss.m.
The middle clock tells you the exact date and time the latest report completed at. So you can interpret the numbers on the pages as being "fresh as of".
The right most clock is a prediction clock for when the next report will complete by. It uses the time taken by the last report plus the configured sleep time to make the prediction.

Is this enough information? Feel free to ask more if you need more information.

**Comment by pjeli** [comment]
As keep in mind, if there is truly some query that you need ran absolutely as near real-time as possible, you can always use the `/filter` and `/histogram` endpoints to run a query.

In #184 and #187, I opened up the `/setCachedQuery` API: https://nnanalytics.readthedocs.io/en/latest/REST_Endpoints/SetCachedQuery/

The above allows you to add a query that will run and cache the result during every report generation run.

**Comment by Viking-Bird** [comment]
Our cluster data volume is PB, which needs to be optimized. Your project is very good, and I hope to become your commiter and write a blog to promote in the Chinese developer community

**Comment by Viking-Bird** [comment]
@pjeli Thanks your answer.Our cluster data volume is PB, which needs to be optimized. Your project is very good, and I hope to become your commiter and write a blog to promote in the Chinese developer community

**Comment by pjeli** [comment]
Thank you so much! I would love the help. It's been just me for a while now!

**Comment by Viking-Bird** [comment]
@pjeli Are you aware of the open source project for YARN monitoring?

**Comment by pjeli** [comment]
Are you referring to Dr. Elephant? If so, you should know that was the inspiration for NNA.

**Comment by pjeli** [comment]
Hey @Viking-Bird, 

I am going to go ahead and close this now. If you want to chat or ask something more feel free to reach me in Gitter or open another issue. :)

Thanks!
