### ISSUE TITLE
Have you ever compiled a dr-elephant?

### ISSUE THREAD

**Issue by Viking-Bird** [paypal/NNAnalytics#257]
I'm sorry I asked you a question unrelated to the project.Have you ever compiled a dr-elephant? I tried to use it to monitor my YANR, but the compilation failed.My compilation environment is centos 6.6 + JDK 1.8 + Play 2.2.6 + Hadoop 2.6.3 + Spark 2.0.1

**Comment by pjeli** [comment]
Yes I have compiled Dr. Elephant. I do not believe you can compile Dr.E with Spark 2.x.

Please reach me over Gitter for talks like this. Would rather prefer not to discuss other projects in Issues.

**Comment by pjeli** [comment]
Closing this out.
