### ISSUE TITLE
Want to get the grammar of NNA sql

### ISSUE THREAD

**Issue by YanjunTian** [paypal/NNAnalytics#273]
Hi team ,
As title , I'd like to use the SQL function of NNA , do you have the SQL grammar or demo guideline documents ?
thanks

**Comment by pjeli** [comment]
Hi @YanjunTian,

So this will be tricky to answer but I will do my best. So, the grammar as used by NNA seems a little lost. NNA only implements the parser, for which the original grammar was taken from JavaCC:
> The parser is built using JavaCC. The core JavaCC grammar for SQL has been taken from Guido Draheim's site and has been changed in order to produce a hierarchy of Java classes. 
- https://github.com/JSQLParser/JSqlParser/wiki

Now as for what are "accepted SQL queries", I will give you some examples and break it down. But basically you can do anything of the form:
* `SELECT * FROM <files,dirs> WHERE <condition1> [AND <condition2>]*`
Example query: `SELECT * FROM files WHERE fileSize = 0`
This will be the equivalent of the NNA style query where you will get a list dump of all the file / directory paths that match your query.
* `SELECT SUM(<field>) FROM <files,dirs> WHERE <condition1> [AND <condition2>]*`
Example query: `SELECT SUM(diskspaceConsumed) FROM files WHERE user = hdfs`
This will be the equivalent of an NNA style query where you perform a summation.
* `SELECT <field1>,SUM(<field2> FROM <files,dirs> WHERE <conditions> GROUP BY <field1> ORDER BY <field1> <ASC/DESC>`
Example query: `SELECT user,SUM(diskspaceConsumed) FROM files GROUP BY user ORDER BY user DESC`
This will be the equivalent of an NNA style query where you perform a grouping of files by their user and a summation for each user grouping.

In place of SUM, you can also perform MIN, MAX, and AVG.
And in the case of GROUP BYs, if you choose to perform the parent directory grouping, you can also set a variable to determine the parent directory depth like you would in NNA style queries, like so:
`SET parentDirDepth = X`, where X is some integer, say 3.

Does this help for now?

**Comment by pjeli** [comment]
All that the NNA SQL-like API does is translate from the SQL query back into an NNA style query. So learning the NNA queries is still recommended to get the most power from NNA.

**Comment by pjeli** [comment]
Another useful piece of information is that the BETWEEN conditions is also supported, like so:
`SELECT * FROM files WHERE accessTime BETWEEN('2018-01-01' 15:00:00 AND '2019-01-01 15:00:00')`

**Comment by YanjunTian** [comment]
yes , helpful to me , thanks

**Comment by pjeli** [comment]
Okay thanks @YanjunTian. I will close this now.
