### ISSUE TITLE
How do I update the two variables that I've highlighted in red?

### ISSUE THREAD

**Issue by Viking-Bird** [paypal/NNAnalytics#289]
![image](https://user-images.githubusercontent.com/12622047/69507536-dc4b5d80-0f6d-11ea-80c2-574b764ce1f4.png)
I notice that it only updates in this method org.apache.hadoop.hdfs.server.namenode.NameNodeLoader.load method,Files and dirs variable are not updated every once in a while when reload is done

**Comment by pjeli** [comment]
Hi @Viking-Bird! Good to hear from you; hope all is well!

I replied to you in Gitter - please let me know if that was enough!

**Comment by Viking-Bird** [comment]
OK,I saw your reply and understand,thank you!
