### ISSUE TITLE
Add simple ContentSummary call

### ISSUE THREAD

**Issue by pjeli** [paypal/NNAnalytics#306]
A majority of the NNAnalytics use-case appears to be off-loading big "getContentSummary" or "hdfs dfs -count" operations off of the Active NameNode. In order to give folks a trivial means of making the transition over to NNA let's open up a REST Endpoint for the call.

/contentSummary?path=<path> should do.

**Comment by lizhi16080910** [comment]
来信已收到，谢谢。
