### ISSUE TITLE
Make suggestions reload sleep configurable

### ISSUE THREAD

**Issue by zero45** [paypal/NNAnalytics#34]
Take a look here:

https://github.com/paypal/NNAnalytics/blob/a73dbc6a5a3dce96fdec027a28e91bdf6789cd1a/src/main/java/org/apache/hadoop/hdfs/server/namenode/NNLoader.java#L1949

We use a hardcoded 15 minute sleep time in NNA in between processing cached user reports.
It would be nice if this could be made configurable as part of the `security.properties`.

** We will eventually change the naming of the `security.properties` file to something like `nna.properties`.

**Comment by pauljv92** [comment]
@zero45 Is it ok to use this.getClass().getClassLoader().getResourceAsStream("security.properties"); for this issue? I dont see any direct reference to the security properties manager class

**Comment by zero45** [comment]
Thanks for looking into this @pauljv92. I think the right approach is going to be eventually passing down SecurityConfiguration (likely will need to be renamed) into NNLoader itself to use when creating the background service thread that eventually calls `reloadSuggestions()`.

**Comment by pauljv92** [comment]
but if we were to change the name to something like nna.properties eventually, we shouldnt be relying on the SecurityConfig class I dont think. Whatre your thoughts on that? But I see where I need to make the code change to make it happen.

**Comment by zero45** [comment]
We will end up renaming SecurityConfiguration as well.

**Comment by pauljv92** [comment]
@zero45 changes made, now how can I validate this issue?
