### ISSUE TITLE
Set default values for variables of SecurityConfiguration class

### ISSUE THREAD

**Issue by pauljv92** [paypal/NNAnalytics#48]
We are currently reading the properties of the SecurityConfiguration class through the values in the security.properties file. However, we should add some default values for this class for when the values do not exist in security.properties. Only assign defaults for the numbers.

**Comment by zero45** [comment]
Linking to #47 because in the comments there we discuss why this is necessary.

**Comment by kunalmulwani** [comment]
I have a question regarding the default values for SecurityConfiguration class. The values present in the security.properties file are to be used as default values or there are different set of values to be used as default values?

**Comment by zero45** [comment]
Right, let's be explicit:

We want to use the following programmatic default values from `src/main/resouces/config/security.properties`:
```
nna.port=8080
nna.historical=false
ldap.enable=false
authorization.enable=false
ldap.use.starttls=false
ldap.connect.timeout=1000
ldap.response.timeout=1000
nna.suggestions.reload.sleep.ms=900000
```

`nna.suggestions.reload.sleep.ms` is the only one thats not listed explicitly. The rest of them we should not use the default as they are things like passwords and keys.

**Comment by kunalmulwani** [comment]
I get permission denied when I try to push my changes for this issue.

**Comment by zero45** [comment]
Are you working on your own fork? You will not be able to push to the `paypal/NNA` repository without writer privileges, which are only given to committers to the project.

**Comment by kunalmulwani** [comment]
My bad. I Will fork and submit a PR after I am done with the changes.
