### ISSUE TITLE
Some 'Totals' queries are broken because of 'filters' instead of 'filter'

### ISSUE THREAD

**Issue by edhart** [paypal/NNAnalytics#63]
Some 'Totals' queries are broken because of 'filters' instead of 'filter'.

For example the following doesn't work:  [web_server:port]/value.html?set=files&filter**s**=fileSize:eq:0&sum=count

But if you change 'filters' to 'filter' it works fine:  [web_server:port]/value.html?set=files&filter=fileSize:eq:0&sum=count

Broken queries include:

- Sum of all Empty Files
- Sum of all Empty Directories
- Sum of all Snapshot'd Files
- Total Snapshot'd Diskspace

**Comment by zero45** [comment]
Thanks for reporting this @edhart. Are you interested in taking this up?

**Comment by edhart** [comment]
Sure!  I a total n00b to github, but I'd be happy to use this opportunity
to learn the ropes if you're OK with it.

By the way, I was quite excited to try out NNA after your session during
the DataWorks summit - and so far I've been quite impressed :)

Thanks again for creating it

**Comment by zero45** [comment]
No worries I'll be happy to guide you! Start off with forking the repo for now.
Here is some documentation on how to do so: https://gist.github.com/Chaser324/ce0505fbed06b947d962

Once you have your changes ready just make a Pull Request that references your fork.

And thank you for the kind words. :) I hope you enjoyed the talk!

**Comment by zero45** [comment]
This is actually a breaking change. I need to revert this. I believe the issue here is instead that if you have no empty files, snapshot files, etc -- you do not get a value of 0 but instead the page appears empty. Using 'filters' was the correct keyword.
